### ISSUE TITLE
Port drush wxt-cex command to Drush 9

### ISSUE THREAD

**Issue by nathanv** [drupalwxt/wxt#110]
Currently, on Drush 9 wxt-cex command does not work. The command needs to be written. I will be doing this.
Resources I'll be using:
https://gbyte.co/blog/creating-drush-9-commands-and-porting-legacy-commands
http://www.drush.org/api/master/Drush/Commands/core/DocsCommands.html#method_configExport

Code I need to port: https://github.com/drupalwxt/wxt/blob/8.x-2.x/modules/custom/wxt_ext/wxt_ext_config/wxt_ext_config.drush.inc

**Comment by nathanpw** [comment]
I took a stab at porting this for drush 9 and seems to work for new and changed configs. I didn't fully test all scenarios. Also, not sure if this is still useful/required. If not maybe we should remove it all together.

[port-wxt-cex-to-drush-9.patch.txt](https://github.com/drupalwxt/wxt/files/4519143/port-wxt-cex-to-drush-9.patch.txt)

**Comment by nathanpw** [comment]
moving this issue to d.o https://www.drupal.org/project/wxt/issues/3130149

**Comment by nathanpw** [comment]
Will be implemented in 3.0.9
