### ISSUE TITLE
8.6 Installer now failing

### ISSUE THREAD

**Issue by rgalipeau** [drupalwxt/wxt#123]
Tarball is now ok, although it now goes through the installer process as per previous versions... it triggers following errors (straight up DevDesktop)... maybe try to replicate?:

An AJAX HTTP error occurred.
HTTP Result Code: 200
Debugging information follows.
Path: /core/install.php?rewrite=ok&profile=wxt&langcode=en&continue=1&id=1&op=do_nojs&op=do
StatusText: OK
ResponseText: Drupal\Core\Config\UnmetDependenciesException: Configuration objects provided by <em class="placeholder">wxt_admin</em> have unmet dependencies: <em class="placeholder">rdf.mapping.comment.comment (rdf)</em> in Drupal\Core\Config\UnmetDependenciesException::create() (line 98 of /Users/robingalipeau/Sites/devdesktop/wxt-8.x-2.200/core/lib/Drupal/Core/Config/UnmetDependenciesException.php).

**Comment by sjpeters79** [comment]
Thanks for mentioning this. I'll take a look.

**Comment by sjpeters79** [comment]
@rgalipeau Please try the latest tarball:
https://github.com/drupalwxt/wxt/releases/download/2.2.1/wxt-8.x-2.210.tar.gz

**Comment by rgalipeau** [comment]
Thanks @sjpeters79. Still getting same error.
Were you able to replicate... Which version of DevDesktop did you use?
I'm using latest DevDesktop 2

**Comment by rgalipeau** [comment]
This works fine now.

**Comment by nfrenette** [comment]
Hi guys,
Just tried installing this tarball and got the same error by doing standard web install, not using DevDesktop.
Should I open a new issue for this?
Thanks!
Nick

**Comment by rgalipeau** [comment]
Are you using php 7.1 or higher?

**Comment by nfrenette** [comment]
Hi Robin,
Yes, we're using 7.1.8. I've successfully installed 8.x-2.190.
Thanks!

**Comment by rgalipeau** [comment]
Great, don’t hesitate to post other issues. I’ll close this.
