### ISSUE TITLE
Composer install

### ISSUE THREAD

**Issue by rgalipeau** [drupalwxt/wxt#126]
Hey guys... if I run 
`composer create-project drupalwxt/wxt-project:8.x-dev MYPROJECT --no-interaction
`
I get Drupal WxT 8.5.6  ??

Also, I get a notice about react
`Package react/socket-client is abandoned, you should avoid using it. Use react/socket instead.
`

**Comment by zachomedia** [comment]
Updated wxt-project with https://github.com/drupalwxt/wxt-project/commit/7ed3b8fb7c0fde29241eb7fb6b238ddc394a49f4

(I haven't tested yet, but should be good now)

**Comment by rgalipeau** [comment]
This now works. Do you not use composer internally when doing builds? (just curious as to how we go to 8.6 without anyone else running into this? @zachomedia @sylus 

P.S. DevDesktop 2 and php 7.1 tested also. (works great).

I'm closing Issue as it works, but curious how anyone was able to test/launch without composer @zachomedia change now pointing to 2.2.1 ?

**Comment by zachomedia** [comment]
We don't use wxt-project internally, we have a different project structure/scaffold system.

Also, once you've done the initial setup with `composer create-project`, it doesn't use wxt-project anymore. You would just update composer.json to point at the new WxT.

**Comment by rgalipeau** [comment]
Thanks Zach. Nice to see the buildout work. (Also had composer Mojave related issue locally which needed update on xcode), but got through it a few weeks ago.

I'll test a clean tarball with DevDesktop and see if that's all good next.
