### ISSUE TITLE
Tarball installation issue with wxt8.x-2.212

### ISSUE THREAD

**Issue by PCH-TanB** [drupalwxt/wxt#138]
An AJAX HTTP error occurred.
HTTP Result Code: 200
Debugging information follows.
Path: /wxt-8.x-2.212/core/install.php?rewrite=ok&profile=wxt&langcode=en&id=1&op=do_nojs&op=do
StatusText: OK
ResponseText: Error: Class 'phpDocumentor\Reflection\DocBlockFactory' not found in Drupal\lightning_core\UpdateManager->__construct() (line 87 of /sites/intra/htdocs/wxt-8.x-2.212/modules/contrib/lightning_core/src/UpdateManager.php).

**Comment by zachomedia** [comment]
@PCH-TanB Can you try this with the tarball that was released this morning?

If you still have issues, can you provide your OS and PHP version.

**Comment by PCH-TanB** [comment]
@zachomedia , Super, it works fine. Thank you very much!

**Comment by rgalipeau** [comment]
@PCH-TanB We had the same issue with the Tarball testing. 7.1 php was the only version that worked, but did not test against this latest tarball.

**Comment by zachomedia** [comment]
@PCH-TanB Thanks, I'll marked this as resolved for now. If you encounter any other issues, please let us know.

**Comment by PCH-TanB** [comment]
@zachomedia Because DrupalWxT is for our Intranet site, Composer is not allowed and access to Internet is not allowed neither, we are only able to install with Tarball from browser. We only successfully installed with version 2.1.9 and this latest 2.1.13. Thanks again for your saving us.

**Comment by zachomedia** [comment]
@PCH-TanB Out of curiosity, what version of PHP are you running? It might be an issue based on what's used when generating the tarball.

**Comment by PCH-TanB** [comment]
@zachomedia, our PHP version is 7.1.8, thank you so much!

**Comment by PCH-TanB** [comment]
@zachomedia, would you please be able to do the same patching with future releases? It would be very very grateful!

**Comment by zachomedia** [comment]
Yeah, I'm going to try and figure out why the 2.212 tarball didn't work so that we can prevent it from happening again.

**Comment by PCH-TanB** [comment]
@zachomedia, regarding with 2.212, firstly, it doesn't include lighting  under /wxt-8.x-2.212/profiles; secondly after I downloaded lighting and extracted it to /wxt-8.x-2.212, then I have the issue from this case when I install. Although versions of 2.1.10, 2.1.11, 2.1.12 have lighting, but have the similar issue from this case. Thanks a lot!

**Comment by mankev** [comment]
Can we re-open this issue? I am getting the exact same error when installing on Acquia Cloud. Further error below. The rest of the stack trace follows:

Additional uncaught exception thrown while handling exception.
Original
Drupal\Core\Config\UnmetDependenciesException: Configuration objects provided by <em class="placeholder">wxt</em> have unmet dependencies: <em class="placeholder">block.block.languageswitcher (wxt_library)</em> in Drupal\Core\Config\UnmetDependenciesException::create() (line 98 of /mnt/www/html/ireneqhnuq3vsxz/docroot/core/lib/Drupal/Core/Config/UnmetDependenciesException.php).

Drupal\Core\Config\UnmetDependenciesException::create('wxt', Array) (Line: 496)
Drupal\Core\Config\ConfigInstaller->checkConfigurationToInstall('module', 'wxt') (Line: 132)
Drupal\Core\ProxyClass\Config\ConfigInstaller->checkConfigurationToInstall('module', 'wxt') (Line: 150)
Drupal\Core\Extension\ModuleInstaller->install(Array, ) (Line: 83)
Drupal\Core\ProxyClass\Extension\ModuleInstaller->install(Array, ) (Line: 1670)
install_install_profile(Array) (Line: 715)
install_run_task(Array, Array) (Line: 590)
install_run_tasks(Array, NULL) (Line: 125)
install_drupal(Object) (Line: 44)
Additional
Drupal\Component\Plugin\Exception\PluginNotFoundException: The "user_role" entity type does not exist. in Drupal\Core\Entity\EntityTypeManager->getDefinition() (line 133 of /mnt/www/html/ireneqhnuq3vsxz/docroot/core/lib/Drupal/Core/Entity/EntityTypeManager.php).

Drupal\Core\Entity\EntityTypeManager->getDefinition('user_role', 1) (Line: 54)
Drupal\Core\Entity\EntityManager->getDefinition('user_role') (Line: 117)
Drupal\Core\Field\Plugin\Field\FieldType\EntityReferenceItem::schema(Object) (Line: 713)
Drupal\Core\Field\BaseFieldDefinition->getSchema() (Line: 736)
Drupal\Core\Field\BaseFieldDefinition->getColumns() (Line: 388)
Drupal\Core\Entity\Sql\DefaultTableMapping->getColumnNames('roles') (Line: 382)
Drupal\views\EntityViewsData->mapFieldDefinition('user__roles', 'roles', Object, Object, NULL) (Line: 283)
Drupal\views\EntityViewsData->getViewsData() (Line: 16)
Drupal\user\UserViewsData->getViewsData() (Line: 170)
views_views_data()
call_user_func_array('views_views_data', Array) (Line: 392)
Drupal\Core\Extension\ModuleHandler->invoke('views', 'views_data') (Line: 243)
Drupal\views\ViewsData->getData() (Line: 160)
Drupal\views\ViewsData->get('block_content') (Line: 91)
Drupal\views\Plugin\Derivative\ViewsEntityRow->getDerivativeDefinitions(Array) (Line: 101)
Drupal\Component\Plugin\Discovery\DerivativeDiscoveryDecorator->getDerivatives(Array) (Line: 87)
Drupal\Component\Plugin\Discovery\DerivativeDiscoveryDecorator->getDefinitions() (Line: 284)
Drupal\Core\Plugin\DefaultPluginManager->findDefinitions() (Line: 175)
Drupal\Core\Plugin\DefaultPluginManager->getDefinitions() (Line: 147)
views_theme(Array, 'module', 'views', 'core/modules/views') (Line: 447)
Drupal\Core\Theme\Registry->processExtension(Array, 'views', 'module', 'views', 'core/modules/views') (Line: 334)
Drupal\Core\Theme\Registry->build() (Line: 233)
Drupal\Core\Theme\Registry->get() (Line: 86)
Drupal\Core\Utility\ThemeRegistry->initializeRegistry() (Line: 67)
Drupal\Core\Utility\ThemeRegistry->__construct('theme_registry:runtime:seven', Object, Object, Array, 1) (Line: 253)
Drupal\Core\Theme\Registry->getRuntime() (Line: 142)
Drupal\Core\Theme\ThemeManager->render('html', Array) (Line: 437)
Drupal\Core\Render\Renderer->doRender(Array, 1) (Line: 195)
Drupal\Core\Render\Renderer->render(Array, 1) (Line: 139)
Drupal\Core\Render\Renderer->Drupal\Core\Render\{closure}() (Line: 582)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 140)
Drupal\Core\Render\Renderer->renderRoot(Array) (Line: 66)
Drupal\Core\Render\BareHtmlPageRenderer->renderBarePage(Array, 'Error', 'install_page', Array) (Line: 76)
Drupal\Core\ProxyClass\Render\BareHtmlPageRenderer->renderBarePage(Array, 'Error', 'install_page', Array) (Line: 1073)
install_display_output(Array, Array, Array) (Line: 260)
_drupal_log_error(Array, 1) (Line: 602)
_drupal_exception_handler(Object)


Thanks

**Comment by zachomedia** [comment]
@mankev Can you please open a new issue for that since you're getting a different error?

**Comment by mankev** [comment]
It's actually the same error. I am getting the exact same message as the original post (I should have mentioned this, my bad) but in Acquia they also link to the log where you can get the stack trace, this is what I added above. I used the tarball at https://ftp.drupal.org/files/projects/wetkit-7.x-4.31-core.tar.gz

I also noticed that the "Try it for yourself at: http://simplytest.me/project/wetkit" is also failing, but this may be unrelated as there is no error message to compare.

I can open a new ticket with the original message and the stack trace if you wish.

**Comment by zachomedia** [comment]
@mankev This repo is for Drupal 8. Can you please open an issue against the Drupal 7 issue queue?https://www.drupal.org/project/issues/wetkit

@sylus tells me simplytest.me has been broken for a while (and for many projects)

**Comment by mankev** [comment]
@zachomedia Sorry did a quick search to get that link and got the drupal 7 instead. Just did another build with https://ftp.drupal.org/files/projects/wxt-8.x-2.213-core.tar.gz on Acquia and got  the errors below.  The first part of the error matches the original post. I was going to confirm on a local machine but I don't have that setup yet.

An AJAX HTTP error occurred.
HTTP Result Code: 200
Debugging information follows.
Path: /core/install.php?rewrite=ok&profile=wxt&langcode=en&id=1&op=do_nojs&op=do
StatusText: OK
ResponseText: Error: Class 'phpDocumentor\Reflection\DocBlockFactory' not found in Drupal\lightning_core\UpdateManager->__construct() (line 87 of /mnt/www/html/ireneqhnuq3vsxz/docroot/profiles/wxt/modules/contrib/lightning_core/src/UpdateManager.php).


Additional uncaught exception thrown while handling exception.
Original
Drupal\Core\Config\UnmetDependenciesException: Configuration objects provided by <em class="placeholder">wxt</em> have unmet dependencies: <em class="placeholder">block.block.languageswitcher (wxt_library)</em> in Drupal\Core\Config\UnmetDependenciesException::create() (line 98 of /mnt/www/html/ireneqhnuq3vsxz/docroot/core/lib/Drupal/Core/Config/UnmetDependenciesException.php). 
Drupal\Core\Config\UnmetDependenciesException::create('wxt', Array) (Line: 496)
Drupal\Core\Config\ConfigInstaller->checkConfigurationToInstall('module', 'wxt') (Line: 132)
Drupal\Core\ProxyClass\Config\ConfigInstaller->checkConfigurationToInstall('module', 'wxt') (Line: 150)
Drupal\Core\Extension\ModuleInstaller->install(Array, ) (Line: 83)
Drupal\Core\ProxyClass\Extension\ModuleInstaller->install(Array, ) (Line: 1670)
install_install_profile(Array) (Line: 715)
install_run_task(Array, Array) (Line: 590)
install_run_tasks(Array, NULL) (Line: 125)
install_drupal(Object) (Line: 44)

Additional
Drupal\Component\Plugin\Exception\PluginNotFoundException: The "user_role" entity type does not exist. in Drupal\Core\Entity\EntityTypeManager->getDefinition() (line 133 of /mnt/www/html/ireneqhnuq3vsxz/docroot/core/lib/Drupal/Core/Entity/EntityTypeManager.php). 
Drupal\Core\Entity\EntityTypeManager->getDefinition('user_role', 1) (Line: 54)
Drupal\Core\Entity\EntityManager->getDefinition('user_role') (Line: 117)
Drupal\Core\Field\Plugin\Field\FieldType\EntityReferenceItem::schema(Object) (Line: 713)
Drupal\Core\Field\BaseFieldDefinition->getSchema() (Line: 736)
Drupal\Core\Field\BaseFieldDefinition->getColumns() (Line: 388)
Drupal\Core\Entity\Sql\DefaultTableMapping->getColumnNames('roles') (Line: 382)
Drupal\views\EntityViewsData->mapFieldDefinition('user__roles', 'roles', Object, Object, NULL) (Line: 283)
Drupal\views\EntityViewsData->getViewsData() (Line: 16)
Drupal\user\UserViewsData->getViewsData() (Line: 170)
views_views_data()
call_user_func_array('views_views_data', Array) (Line: 392)
Drupal\Core\Extension\ModuleHandler->invoke('views', 'views_data') (Line: 243)
Drupal\views\ViewsData->getData() (Line: 160)
Drupal\views\ViewsData->get('block_content') (Line: 91)
Drupal\views\Plugin\Derivative\ViewsEntityRow->getDerivativeDefinitions(Array) (Line: 101)
Drupal\Component\Plugin\Discovery\DerivativeDiscoveryDecorator->getDerivatives(Array) (Line: 87)
Drupal\Component\Plugin\Discovery\DerivativeDiscoveryDecorator->getDefinitions() (Line: 284)
Drupal\Core\Plugin\DefaultPluginManager->findDefinitions() (Line: 175)
Drupal\Core\Plugin\DefaultPluginManager->getDefinitions() (Line: 147)
views_theme(Array, 'module', 'views', 'core/modules/views') (Line: 447)
Drupal\Core\Theme\Registry->processExtension(Array, 'views', 'module', 'views', 'core/modules/views') (Line: 334)
Drupal\Core\Theme\Registry->build() (Line: 233)
Drupal\Core\Theme\Registry->get() (Line: 86)
Drupal\Core\Utility\ThemeRegistry->initializeRegistry() (Line: 67)
Drupal\Core\Utility\ThemeRegistry->__construct('theme_registry:runtime:seven', Object, Object, Array, 1) (Line: 253)
Drupal\Core\Theme\Registry->getRuntime() (Line: 142)
Drupal\Core\Theme\ThemeManager->render('html', Array) (Line: 437)
Drupal\Core\Render\Renderer->doRender(Array, 1) (Line: 195)
Drupal\Core\Render\Renderer->render(Array, 1) (Line: 139)
Drupal\Core\Render\Renderer->Drupal\Core\Render\{closure}() (Line: 582)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 140)
Drupal\Core\Render\Renderer->renderRoot(Array) (Line: 66)
Drupal\Core\Render\BareHtmlPageRenderer->renderBarePage(Array, 'Error', 'install_page', Array) (Line: 76)
Drupal\Core\ProxyClass\Render\BareHtmlPageRenderer->renderBarePage(Array, 'Error', 'install_page', Array) (Line: 1073)
install_display_output(Array, Array, Array) (Line: 260)
_drupal_log_error(Array, 1) (Line: 602)
_drupal_exception_handler(Object)

**Comment by sylus** [comment]
I wonder if this is the php version, can you verify your on php 7.2?

**Comment by mankev** [comment]
Yes it is php 7.2.

**Comment by sylus** [comment]
Oh we just saw from your notes that you were grabbing the tars from drupal.org which currently has an issue with make file packaging. All distributions have this you have to use our tarball hosted on github that we generate ourselves.

You can see the specific line that fixes your issue right here:

https://github.com/drupalwxt/wxt/blob/8.x-2.x/tarball.sh#L14

**Comment by sylus** [comment]
https://github.com/drupalwxt/wxt/releases/download/2.2.13/wxt-8.x-2.213.tar.gz

**Comment by mankev** [comment]
The environment allows me to switch between php 7.1 and 7.2. 
Tried the build with 7.1 and received the same error. It fails at about the 75% mark after installing the libraries module.

**Comment by zachomedia** [comment]
Which tarball are you using? The ones on drupal.org will not work due to a packaging issue with the environment. We release a fully functional tarball on github.com: https://github.com/drupalwxt/wxt/releases/download/2.2.13/wxt-8.x-2.213.tar.gz

**Comment by mankev** [comment]
OK that fixed it. Thanks a lot.
