### ISSUE TITLE
Aurora design system

### ISSUE THREAD

**Issue by mgifford** [drupalwxt/wxt#142]
Are you leveraging the Aurora design system? https://design.gccollab.ca/

Hopefully there is some collaboration, but who knows https://github.com/gctools-outilsgc/design-system-code/issues/208

So many silos in government.  Just cross-positing so that there's a tread.

**Comment by zachomedia** [comment]
@sylus says he's working on it. It's possible it will be here in a couple of weeks, but it's not high priority at the moment.

**Comment by sylus** [comment]
Unfortunately this didn't end up happening as Aurora theme uses Bootstrap 4 and we need to wait for Drupal.org Bootstrap project to support that.

Lets move this issue over to Drupal.org where it can stay open as an issue we would like to work on :D

**Comment by mgifford** [comment]
Moved https://www.drupal.org/project/wxt/issues/3154175
