### ISSUE TITLE
Add list of new configurations to the changelog and release notes

### ISSUE THREAD

**Issue by minorOffense** [drupalwxt/wxt#151]
If new configurations are required between releases and the update hooks don't take care of them then they should be listed in the release notes for site maintainers to import.

**Comment by zachomedia** [comment]
We typically document such manual updates if they are not in update hooks.

Is there a specific example where this did not occur?

**Comment by minorOffense** [comment]
@sjpeters79 mentioned there were a few things that might have been missed. I'll get him to chime on what needs to be added.

This was part of a meeting we had at the office yesterday. Trying to make a list of stuff go help document WxT for other departments to use and update the WxT website accordingly.

Thinking maybe we could add a commit comment tag or something to track config changes to generate docs or something...
