### ISSUE TITLE
Tarball installation issue with wxt8.x-2.214 and wxt8.x-2.215

### ISSUE THREAD

**Issue by PCH-TanB** [drupalwxt/wxt#152]
I got the following error:
Additional uncaught exception thrown while handling exception.
Original

Drupal\Core\Extension\Exception\UnknownExtensionException: The profile lightning does not exist. in Drupal\Core\Extension\ExtensionList->get() (line 257 of /sites/intra/htdocs/wxt-8.x-2.214/core/lib/Drupal/Core/Extension/ExtensionList.php).

Drupal\Core\Extension\ExtensionList->get('lightning') (Line: 62)
Drupal\Core\Extension\ProfileExtensionList->getAncestors('wxt') (Line: 266)
Drupal\Core\Extension\ExtensionDiscovery->setProfileDirectoriesFromSettings() (Line: 178)
Drupal\Core\Extension\ExtensionDiscovery->scan('module') (Line: 148)
drupal_required_modules() (Line: 1126)
install_profile_info('wxt', 'en') (Line: 1548)
install_load_profile(Array) (Line: 473)
install_begin_request(Object, Array) (Line: 122)
install_drupal(Object) (Line: 44)

Additional

Drupal\Core\Extension\Exception\UnknownExtensionException: The profile lightning does not exist. in Drupal\Core\Extension\ExtensionList->get() (line 257 of /sites/intra/htdocs/wxt-8.x-2.214/core/lib/Drupal/Core/Extension/ExtensionList.php).

Drupal\Core\Extension\ExtensionList->get('lightning') (Line: 62)
Drupal\Core\Extension\ProfileExtensionList->getAncestors() (Line: 169)
Drupal\Core\Config\InstallStorage->getAllFolders() (Line: 109)
Drupal\Core\Config\InstallStorage->exists('core.extension') (Line: 103)
Drupal\Core\Config\FileStorage->read('core.extension') (Line: 130)
Drupal\Core\Config\FileStorage->readMultiple(Array) (Line: 165)
Drupal\Core\Config\ConfigFactory->doLoadMultiple(Array, 1) (Line: 104)
Drupal\Core\Config\ConfigFactory->doGet('core.extension') (Line: 89)
Drupal\Core\Config\ConfigFactory->get('core.extension') (Line: 221)
Drupal\Core\Extension\ThemeHandler->refreshInfo() (Line: 188)
Drupal\Core\Extension\ThemeHandler->listInfo() (Line: 63)
_drupal_maintenance_theme() (Line: 742)
drupal_maintenance_theme() (Line: 1040)
install_display_output(Array, Array, Array) (Line: 260)
_drupal_log_error(Array, 1) (Line: 602)
_drupal_exception_handler(Object)

![image](https://user-images.githubusercontent.com/2203586/54767863-70da1080-4bd4-11e9-8916-39d8ae6f2a86.png)

**Comment by zachomedia** [comment]
Looks like the lightning profile was missing from the some of the generated tarballs. I have regenerate the tarball for the last release with lightning.

We are adding a check to our release process to catch this before the tarball is released.
