### ISSUE TITLE
Update field_group to 3.0?

### ISSUE THREAD

**Issue by joel-osc** [drupalwxt/wxt#163]
What are people's thoughts on including field_group 3.0 instead of 1.0? The maintainer is recommended 3.0-beta instead of 1.0 now. The reason I ask is that there is a great patch available for the 3.0 branch (https://www.drupal.org/project/field_group/issues/2652642) that allows you to move fields into the right column on node edit.

https://www.drupal.org/project/field_group

**Comment by sjpeters79** [comment]
Noticed that as well. There's an RC1 out for it now.

**Comment by sylus** [comment]
@sjpeters79 would you mind taking a look at this? Does the data structure change for yml exports? I don't see any update hooks so looks triival. If is just a simple switch then I can make the switch quickly. Just wanted to make sure wxt_admin is still good as does use field_group settings for groupings. Let me know ^_^

**Comment by sylus** [comment]
Will track this issue over at https://www.drupal.org/project/wxt/issues/3080003
