### ISSUE TITLE
Critical issue of entity_reference 

### ISSUE THREAD

**Issue by PCH-TanB** [drupalwxt/wxt#164]
We tried to install wxt8.x-2.13 to wxt8.x-2.18 and found this critical issue of entity_reference 👍 
The field_slideshow_items entity reference field (entity_type: block_content, bundle: media_slideshow) no longer has any valid bundle it can reference. The field is not working correctly anymore and has to be adjusted.
![image](https://user-images.githubusercontent.com/2203586/57861024-e5d85980-77c3-11e9-83f5-9152a7b5e5b2.png)

**Comment by sylus** [comment]
I think this was an issue with upstream media that has now been corrected. Is still persists please file an issue over at drupal.org/project/wxt with replication steps and can take a look :D
