### ISSUE TITLE
Error exporting key_value_expire table

### ISSUE THREAD

**Issue by nfrenette** [drupalwxt/wxt#167]
The key_value_expire table was somehow corrupted in our production environment and we are unable to export it to synchronize our development environments.

Can this cause any critical issues? Can we exclude it from our export, or truncate the table, without causing any issues?

It seems to only hold temporary work in progress:
"Typically, the PrivateTempStore might be used to store work in progress that is later saved permanently elsewhere, e.g. autosave data, multistep forms, or in-progress changes to complex configuration that are not ready to be saved."

Thank you

**Comment by sjpeters79** [comment]
https://drupal.stackexchange.com/questions/221985/what-is-the-purpose-of-key-value-expire-table

**Comment by nfrenette** [comment]
Thanks! This is actually the only resource I had found. From what I gather, it doesn't seem critical and can probably be truncated without any issues based on how simple our installation is. We will test and report back any errors.
Cheers,
Nick

**Comment by sjpeters79** [comment]
Yeah it's not critical.
