### ISSUE TITLE
Update Drupal.org

### ISSUE THREAD

**Issue by mgifford** [drupalwxt/wxt#187]
This is out of date. If the zip file isn't being maintained it shouldn't be green. 

https://www.drupal.org/project/wxt

**Comment by zachomedia** [comment]
Can you clarify what you mean? The release is green as it's our recommended version.

The zip file requires an additional step to install, as mentioned on the page:

> The tarball distributed here on drupal.org is deprecated and does not install correctly because drupal.org does not package WxT's Composer dependencies. 
> 
> To work around this, we are providing tarballs on our GitHub page, which contain the required dependencies and will work properly. Visit our list of releases on GitHub, and under "Downloads", grab the desired wxt-VERSION.tar.gz file.
>
> If you MUST use the tarball here on drupal.org, you will still need Composer installed. Once you extract the tarball, run the following command from within your web root to install the required dependencies:
>
> `composer require j7mbo/twitter-api-php league/oauth2-server:~6.0 webflo/drupal-core-strict:~8.7.0 'phpdocumentor/reflection-docblock:^3.0||^4.0'`

This is identical to what Lightning does.

**Comment by mgifford** [comment]
Most of the Drupal world doesn't start with Lightning.  They start with Core.  That should be the assumption that should be taken in writing any documentation.  If you need to point folks to Lightning as the base of your documentation, that is just fine.

**Comment by zachomedia** [comment]
I'm not sure I'm understanding, the Drupal WxT page on Drupal.org explicitly states all of this.

> ## Architecture
> This install profile directly extends from the Lightning Framework created by Acquia to provide developers with a powerful base toolchain upon which to extend. Due to this strict dependency we also align much of our workflow with the best practice established patterns Acquia has provided.

And then later on talks about how to install it, including the issues with the Drupal.org tarball / zip file.

Also, if someone wants to go the core route, the WxT Bootstrap theme and WxT Libraries modules can be used independently from the distro so that we don't want to force the distribution on everyone. This was a lesson learned from Drupal 7.

Is there something you had in mind to make this more clear?

**Comment by mgifford** [comment]
I'll get back to you with more specific changes.  Best to do so on Drupal.org?

**Comment by zachomedia** [comment]
Yeah, Drupal.org issues would be best for documentation updates, either in the distribution or wxt_bootstrap/wxt_library if you only use those two modules.

I will close this issue for now, pending follow ups on Drupal.org. Feel free to continue the discussion if necessary

We've had a stronger focus recently on the cloud architecture documentation (https://github.com/drupalwxt/helm-drupal/tree/master/docs), but we do hope to improve the others in the new year.

Thanks!
