### ISSUE TITLE
Blog

### ISSUE THREAD

**Issue by mgifford** [drupalwxt/wxt#189]
This project doesn't look like it has been updated in years.  Please write about what you are doing https://drupalwxt.github.io/

A bunch of us want to use this tool, but it doesn't help if it seems like you have to work at StatsCan to know what is happening with the code base.

**Comment by zachomedia** [comment]
While the blog hasn't been updated, the project is actively worked on. In addition, all major features have associated Drupal.org issue with them.

The documentation page on drupalwxt.github.io has been updated this year, and we've been focusing on making sure the README and CHANGELOGS have the information that's needed. You can see this via the Git history.

Also the goal of Drupal WxT is to be lightweight, so it doesn't have a lot of features to maintain. We keep up to date with what Lightning and Drupal Core are doing. The team maintaining this distribution is growing in the new year and we hope to dedicate more time to working on the documentation site.

**Comment by mgifford** [comment]
Thanks for putting more time into the documentation.  Blogs are useful, but not if they aren't updated https://drupalwxt.github.io/post/

I know that there is work being done, but you need to be able to talk about it. Knowing where to ask the questions.  Could even be knowing where your team looks for errors and best way to get in touch.

**Comment by lawrenceong001** [comment]
hi @mgifford -- I am kind of in agreement with you on this. being new to drupal, it's been quite an interesting ride so far to get drupalwxt going. at this time i'm still trying to get a streamlined install going.

**Comment by croeslab** [comment]
Could you please confirm the version of WxT that is being run as part of this project? Would that be WET4 and if so is there any timeline for moving towards the GCWEB template using this repository?

**Comment by nathanpw** [comment]
@croeslab we are using have support for the gcweb 4/5/6 templates. Please see our changelog for the distro and our releases to see which versions of wet-boew are included.: https://github.com/drupalwxt/wxt/blob/8.x-3.x/CHANGELOG.md As mentioned by zachomedia above.

@mgifford we have been documenting as best we can to allow for more transparency, community, and easier "come up to speed". However, it is not our mandate to provide documentation and training. Unfortunately, we do this as a best effort as we are passionate about open source and working in an open space and collaborate best we can. I appreciate any help or suggestions and would happily take input and commitments from the community (or people interested in leveraging Drupal and the wxt distribution).

**Comment by mgifford** [comment]
@nathanpw can you at least say "The WxT is looking for a team to take on the maintenance of the documentation of this project. Please step up, particularly if you have skills in documentation and are a government department. Folks who work for government should also consider contributing."

Something like that.  It's one thing to say, "it's not in our mandate", but what I'd really love to hear is, "this is important and we need to grow the community so that this can happen".
