### ISSUE TITLE
Follow approved country list for addresses

### ISSUE THREAD

**Issue by mgifford** [drupalwxt/wxt#195]
Just did a demo where we realized that Taiwan is available in the list of countries.  The GC doesn't officially recognize Taiwan, Tibet and a few others aren't countries that we officially recognize. That said, the Drupal community does. As much as I'd like to side with the Drupal community, it's kinda inappropriate for the GC, particularly when China is looking for faults. 

Lets make sure that the list of countries is officially recognized.

**Comment by colans** [comment]
> [...] China is looking for faults.

This shouldn't be a reason to do or not do something.  Aligning with official policy for GoC sites is a sound argument, however.

**Comment by sjpeters79** [comment]
Won't do

**Comment by mgifford** [comment]
Sorry @sjpeters79 this isn't acceptable.  

I'm pretty sure that GC policy doesn't recognize Taiwan.  As much as I'd like to recognize Taiwan, DrupalWxT needs to follow federal policy. 

I do not know on what grounds you will close this issue given that you are not hired to develop or interpret international policy.

**Comment by zachomedia** [comment]
@sylus has opened a Drupal.org issue for this in order to bring further discussion on the matter, and whether this should belong in the distribution, a per-site installation requirement or a webform feature request to enable this.

https://drupal.org/node/3111375
