### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by lawrenceong001** [drupalwxt/wxt#200]
hi again folks,

pardon the newb questions. got things running on WSL and also created a project using composer.

so, from a workflow perspective, how do i get this to be displayed? do i need a drupal instance? would it need to run apache? i'm assuming it needs to be backed by some database (mysql)? 

would be great if someone here can provide some tips to help get me going. 

tks for your help!

**Comment by sylus** [comment]
You need to have a local or hosted environment available for your use that meets Drupal 8 system requirements (including working versions of Apache, MySQL, and PHP) or more preferably Nginx. 

Assuming you are not using docker which sets all of this up just folow the official Drupal.org guidance https://www.drupal.org/requirements

Then ensuring you have:

Composer
Node

You can open a command prompt and run:

a) composer create-project drupalwxt/wxt-project:3.0.7 site-name --no-interaction
b) Or just simply grab the tar

Then can do either a GUI install or one via Drush SI. The official drupal docs can help you.

**Comment by lawrenceong001** [comment]
thanks @sylus, I was able to set up drupal on WSL (after all sorts of hoops!). just out of curiosity what is GUI install?

**Comment by zachomedia** [comment]
@lawrenceong001 It would be the installer through the web browser rather than the Drush CLI.
