### ISSUE TITLE
An error occurred trying to check available interface translation updates.

### ISSUE THREAD

**Issue by lawrenceong001** [drupalwxt/wxt#202]
Hello, 

I ran into an issue while using the GUI to configure DrupalWXT. 

environment: 
Win10, WSL1
Ubuntu 18.04
PHP7.2
Nginx 1.14
Drupalwxt (wxt-8.x-3.007.tar.gz)

While configuring Drupal using the graphical user interface, under "install extensions", I received the following error:
<code>An AJAX HTTP error occurred.
HTTP Result Code: 500
Debugging information follows.
Path: /core/install.php?profile=wxt&langcode=en&id=2&op=do_nojs&op=do
StatusText: Internal Server Error
ResponseText: </code>

selected the "please continue to the error page", which shows:
<code>An error occurred trying to check available interface translation updates.</code>

after churning progress for a while, I get a new page with this error
<code>The website encountered an unexpected error. Please try again later.

Drupal\Component\Plugin\Exception\PluginNotFoundException: The "entity_queue" entity type does not exist. in Drupal\Core\Entity\EntityTypeManager->getDefinition() (line 150 of core/lib/Drupal/Core/Entity/EntityTypeManager.php).
</code>
please advise

**Comment by sylus** [comment]
As with the other issue there is likely something wrong with your settings maybe your max_execution_time isn't set high enough or hitting a timeout when trying to pull the translations. We don't hit this in an our of setups whether through just composer on our own nginx servers or via docker. Try to conmpare our php.ini settings and my.cnf settings and see if you can match them.

https://github.com/drupalwxt/docker-scaffold/tree/master/conf

**Comment by lawrenceong001** [comment]
tks @sylus -- I'll get these settings in tonight and report back.

**Comment by lawrenceong001** [comment]
hi @sylus, here's my nginx site config - does this make sense?: 
```
# place this into the file
server {
	server_name _;
	root /var/www/wxt; ## <-- Your only path reference.

	listen 8080;
	listen [::]:8080;
	# listen 443 default ssl;

	#ssl_certificate /etc/nginx/ssl/drupal.crt;
	#ssl_certificate_key /etc/nginx/ssl/drupal.key;

	location = /favicon.ico {
		log_not_found off;
		access_log off;
	}

	location = /robots.txt {
		allow all;
		log_not_found off;
		access_log off;
	}

# Very rarely should these ever be accessed outside of your lan
#location ~* \.(txt|log)$ {
# allow 192.168.0.0/16;
# deny all;
#}

#location ~ \..*/.*\.php$ {
# return 403;
#}

#location ~ ^/sites/.*/private/ {
# return 403;
#}

	# Block access to "hidden" files and directories whose names begin with a
	# period. This includes directories used by version control systems such
	# as Subversion or Git to store control files.
	location ~ (^|/)\. {
		return 403;
	}

	location / {
		# try_files $uri @rewrite; # For Drupal <= 6
		try_files $uri /index.php?$query_string; # For Drupal >= 7
	}

	location @rewrite {
		rewrite ^/(.*)$ /index.php?q=$1;
	}

	# In Drupal 8, we must also match new paths where the '.php' appears in the middle,
	# such as update.php/selection. The rule we use is strict, and only allows this pattern
	# with the update.php front controller. This allows legacy path aliases in the form of
	# blog/index.php/legacy-path to continue to route to Drupal nodes. If you do not have
	# any paths like that, then you might prefer to use a laxer rule, such as:
	# location ~ \.php(/|$) {
	# The laxer rule will continue to work if Drupal uses this new URL pattern with front
	# controllers other than update.php in a future release.
	location ~ '\.php$|^/update.php' {
		fastcgi_split_path_info ^(.+?\.php)(|/.*)$;
		#NOTE: You should have "cgi.fix_pathinfo = 0;" in php.ini
		include fastcgi_params;
		include snippets/fastcgi-php.conf;
		fastcgi_param SCRIPT_FILENAME $request_filename;
		fastcgi_intercept_errors on;
		fastcgi_pass unix:/run/php/php7.2-fpm.sock;
		fastcgi_buffering off;
		fastcgi_read_timeout 300;
	}

	# Fighting with Styles? This little gem is amazing.
	# location ~ ^/sites/.*/files/imagecache/ { # For Drupal <= 6
		location ~ ^/sites/.*/files/styles/ { # For Drpal >= 7
		try_files $uri @rewrite;
	}

	location ~* \.(js|css|png|jpg|jpeg|gif|ico)$ {
		expires max;
		log_not_found off;
	}
}

```

**Comment by sylus** [comment]
Hey @lawrenceong001 I think this is now fixed with you having the correct permissions now ^_^

Please reopen or file in https://drupal.org/project/wxt if that is not the case!

Thanks so much!

**Comment by lawrenceong001** [comment]
hi @sylus, I didn't close this as I still have to replicate the configuration first. seeing as this site wasn't created using composer & drush, I'll revert to trying out the tar file. 

Will let you know if it's solved. 


tks
Lawrence
