### ISSUE TITLE
Possible to remove unexpected padding (left and right) of rendered breadcrumb?

### ISSUE THREAD

**Issue by soliagha-oc** [drupalwxt/wxt#203]
Is it possible to remove unexpected padding (left and right) of rendered breadcrumb?

Drupal 8 WXT

```
<div class="region region-breadcrumb">
  <nav id="wb-bc" property="breadcrumb">
    <h2>You are here</h2>
    <div class="container">
      <ol class="breadcrumb">
        <li><a href="/en">Home</a></li>
        <li class="active">template_controls</li>
      </ol>
    </div>
  </nav>
</div>
```
Computed styles (for class "container"):
border-left-color:rgb(204, 204, 204);
border-left-style:solid;
border-left-width:1px;
border-right-color:rgb(204, 204, 204);
border-right-style:solid;
border-right-width:1px;
box-sizing:border-box;
color:rgb(51, 51, 51);
display:block;
font-family:"Helvetica Neue", Helvetica, Arial, sans-serif;
font-size:16px;
height:45px;
line-height:23px;
margin-left:299px;
margin-right:299px;

padding-left:15px;
padding-right:15px;

text-size-adjust:100%;
width:1170px;
-webkit-tap-highlight-color:rgba(0, 0, 0, 0);

Can we override this WXT Bootstrap class somehow?

Example image: ![Screenshot from 2020-02-13 18-44-56](https://user-images.githubusercontent.com/58790686/74544058-7a6b1600-4f14-11ea-826f-20e49428b42c.png)

**Comment by mgifford** [comment]
This occurs in both the wxt distro as well as the stand alone Drupal theme. 

I don't think this is how breadcrumbs are supposed to look here.

**Comment by mgifford** [comment]
It is also visible in the other theme. 

<img width="531" alt="screenshot with alternate WxT theme" src="https://user-images.githubusercontent.com/116832/74562862-8e753e80-4f39-11ea-9e9e-ece31d0d7e32.png">

**Comment by sylus** [comment]
Hey @soliagha-oc 

I moved this issue over to https://www.drupal.org/project/wxt/issues/3115424 where I also implemented a fix for all of the non gcweb themes and ensured all match expected markup from https://wet-boew.github.io.

Thanks for reporting this and let me know in the other issue if missed anything ^_^

**Comment by duboisp** [comment]
FYI - The web usability theme are not supported anymore.

**Comment by mgifford** [comment]
Good to know @duboisp - where is that documented?

**Comment by sylus** [comment]
Hey @duboisp we still ship with old themes as well as new ones, as this one is the default theme on install even though everyone I know switches to gcweb.

Is there another non government branded theme we can install by default? Ideally not the base theme?

The theme is still the active one in use over at https://wet-boew.github.io
