### ISSUE TITLE
Brand Menu.

### ISSUE THREAD

**Issue by mgifford** [drupalwxt/wxt#205]
What is the Brand menu? Why is it listed as "Brand Menu."? I think the '.' is non-standard. 

When that heading is expressed to screen readers, what should a user understand the menu should contain? I just ran into a GC accessibility report that raised this as a concern. For most users, a brand is like the GC logo, or maybe Starbucks or Walmart. 

What information should a content author put within that Brand menu? The intended use for all of these items could be added to the menu structure to make it easier for people to understand how these menus are intended to be used. 

Plus, this should be documented somewhere.

**Comment by sylus** [comment]
Think this was fixed a bit ago as the yaml is now:

```sh
langcode: en
status: true
dependencies: {  }
id: brand
label: Brand
description: 'Brand Menu used for departmental specific links.'
locked: false
```

If any other issues please file in Drupal.org issue queue :D
