### ISSUE TITLE
Mismatched entity and/or field definitions

### ISSUE THREAD

**Issue by ClassicCut** [drupalwxt/wxt#208]
On the status report page, there is an error in the "entity/field definitions" category. The error is reporting mismatched entity and/or field definitions for user.field_first_name and user_field_last name. The error is:

"Mismatched entity and/or field definitions
The following changes were detected in the entity type and field definitions.

User
- The user.field_first_name field needs to be updated.
- The user.field_last_name field needs to be updated."

see https://www.drupal.org/project/wxt/issues/3122125

**Comment by sylus** [comment]
Committed and attributed, thx!
