### ISSUE TITLE
Install via composer fails - file/path not found

### ISSUE THREAD

**Issue by locutux** [drupalwxt/wxt#215]
Hi all,

I've been trying to install WxT on Windows/IIS using composer (as opposed to tarball), and been consistently running into this error:

```
c:\testD>composer create-project drupalwxt/wxt-project:3.0.8 siteName
Creating a "drupalwxt/wxt-project:3.0.8" project at "./siteName"
Installing drupalwxt/wxt-project (3.0.8)
  - Installing drupalwxt/wxt-project (3.0.8): Loading from cache
    Failed to download drupalwxt/wxt-project from dist: RecursiveDirectoryIterator::__construct(c:\testD/vendor/composer/,c:\testD/vendor/composer/): Le chemin d’accès spécifié est introuvable. (code: 3)
    Now trying to download from source
  - Installing drupalwxt/wxt-project (3.0.8): Cloning 3c6676d7d8


  [UnexpectedValueException]
  RecursiveDirectoryIterator::__construct(C:\testD\siteName,C:\testD\siteName): Le fichier spécifié est introuvable.
  (code: 2)
```

Now, there seems to be some slash/backslash confusion in the parameter passed to the constructor of RecursiveDirectoryIterator. Of course then it won't find the file or the path (code: 3).

Any ideas why this might be? Thanks for any insight.

**Comment by nathanpw** [comment]
I would guess from the messaging it can't download, which suggest an internet/network type issue. Have you tried a different distro or module and see if you get the same message?

That seems like an older version of the distro I think the latest is 3.11, have you tried that?

I am about to tag a new release today. I will try it later today. It might be better to open an issue on d.o as that is generally where we communicate and there is a broader audience (and maybe some windows users). I don't use windows, so I can't speak to that. :P

i.e.: https://www.drupal.org/project/issues/wxt?text=&status=All

**Comment by sylus** [comment]
Lets move this issue over to the Drupal.org issue queue which has a lot more eyes and people that can assist this problem.
