### ISSUE TITLE
Plan for Drupal 9?

### ISSUE THREAD

**Issue by mgifford** [drupalwxt/wxt#217]
So what are the plans for upgrading this distro?  Have folks tried it?

**Comment by rgalipeau** [comment]
I strongly doubt it, with D9 only a few days old, and a large issue queue... this is unlikely until it stabilizes and all module dependencies get there. Dries kept promising it would be easy "upgradable" for the first time, remains to be seen from what we've seen... but again, we're in week 1. Certainly don't expect to be anywhere neat as painful as to the multi-year transition from the D7>D8 mess (Rules D8 module still not stable!)... but suspect it will be a few months before we test this. Also depends on when GC departments will fund this testing. Monitoring Lightning also.

**Comment by mgifford** [comment]
I mostly added this thread so that we could track the progress.  Just checked and Lightning 
 https://www.drupal.org/project/lightning has a beta of 5.0.x which is for 9.0.x.  So might be reasonably far along.

**Comment by rgalipeau** [comment]
It's certainly the promise the D9 (upgrade). I'm sure we will be testing it soon. Have you kicked the can yet?

**Comment by mgifford** [comment]
Frankly only on SimplyTest.me.  I think this is the first time (perhaps since Drupal 5) that I didn't download and test it out early.

**Comment by rgalipeau** [comment]
Lightning still on an RC1 of D9 and in Beta. Starting to review slowly. Keep u posted.

**Comment by nathanpw** [comment]
We had planned to move after lightning (or at least align with them). As far as I know most of the distro specific code should be fine and most contrib (included in the distro/lightning). It would be worthwhile running it all through the linter, as that should help identify any deprecated functions or methods. I just haven't had the time. I did fix some wxt_library issues a couple releases ago (which I think was all that was left for d9).

I would also prefer we have these discussions on d.o (drupal.org) in the wxt project issue queue. As that is the central communication hub for wxt. Appreciate you guys and any help you can provide!

**Comment by nathanpw** [comment]
Update to add that in the next release (3.0.12?) I am updating a bunch of contrib that we have pinned in the distro which will add more Drupal 9. In discussions with the team, I am pretty sure we are going to skip Drupal 8.9 and go right to Drupal 9, which I believe lightning is doing also.

**Comment by sylus** [comment]
There is an issue for this in D.O we working on and i have a branch that is mostly ready for this. 

Thankfully there wasn't much changes to do.

Lets continue this work over in D.O thanks!

**Comment by gardon** [comment]
@sylus it would be helpful to everyone who follows this to have the link to the issue you mentioned.

**Comment by sylus** [comment]
Sure thing here it is: 

https://www.drupal.org/project/wxt/issues/3154403

We just want to try to have all of the issues in one centralized place as many developers don't check here on GitHub.

Thanks!
