### ISSUE TITLE
Updating from 2.2.19 to 3.0.12 breaks panelizer

### ISSUE THREAD

**Issue by kevinabruner** [drupalwxt/wxt#225]
Per my last issue, I was able to update to 3.0.12. However, this site was used favouring panelizer and having disabled Layout Builder entirely since apparently my predecssor had issues with both being enabled at the same time. I see that Layout Builder is now mandatory for WxT Admin and other modules. We are indeed having strange behaviour with panelizer with Layout Builder now enabled. Specifically, when editing the layout of a basic page content type (structure/types/manage/page/display), if one tries to click "edit" on the default displays at the bottom of the page, this results in a 404. 

Is there either a way to disable Layout Builder in version 3.0+ _or_ is there a way to use panelizer with Layout Builder enabled that I'm missing?

![Capture](https://user-images.githubusercontent.com/17281245/91484962-05d84300-e878-11ea-92d1-244f17a31036.JPG)
![Capture2](https://user-images.githubusercontent.com/17281245/91485005-1983a980-e878-11ea-8521-5ca04f0af062.JPG)

**Comment by sylus** [comment]
Can you file this issue on D.O since more developers look over there? 

Thanks :D
