### ISSUE TITLE
Drupal 8 support to end November 2021

### ISSUE THREAD

**Issue by smitsco** [drupalwxt/wxt#227]
Hi there,

Wondering if plans/work is underway to move Drupal WxT to Drupal 9?

Article mentions end of support date November 2021: https://www.drupal.org/docs/understanding-drupal/drupal-9-release-date-and-what-it-means/what-happens-to-drupal-8-now-that

Thank you,
Scott Smith

**Comment by sylus** [comment]
Yes there is and progress is ongoing, there is an issue over at https://drupal.org/project/wxt tracking this!

Thanks :)
