### ISSUE TITLE
Drupal Security Advisory Security risk: Critical

### ISSUE THREAD

**Issue by PCH-TanB** [drupalwxt/wxt#233]
Hello, it seems that the latest version of drupalwxt 3.0.17(drupal core 8.8.10) is affected. When is the patch available?
See details here https://cyber.gc.ca/en/alerts/drupal-security-advisory-10 and https://www.drupal.org/sa-core-2020-012.
Thanks a lot!
Bobby

**Comment by zachomedia** [comment]
@PCH-TanB Can you elaborate where you're seeing 8.8.10? https://github.com/drupalwxt/wxt/blob/3.0.17/composer.json#L19 points to 8.8.11 and the lock file that was auto-generated by the release (https://github.com/drupalwxt/site-wxt/blob/8.x/composer.lock#L3614) also has 8.8.11.

**Comment by PCH-TanB** [comment]
![image](https://user-images.githubusercontent.com/2203586/99829155-ec1e6300-2b29-11eb-9a1e-846cc11e0923.png)

**Comment by sylus** [comment]
Oh that was just an accident in the README.md I have updated that but the codebase itself is the correct version.

Fixed the README.md @PCH-TanB  thanks :D
