### ISSUE TITLE
 wxt-8.x-3.0.18: The configuration property settings.allowed_values.0.label.0 doesn't exist

### ISSUE THREAD

**Issue by PCH-TanB** [drupalwxt/wxt#237]
Hello when I run drush update:wxt and with  Do you want to enable additional slideshow enhancements? (yes/no) [yes]:Yes.
Then I got this error:
![image](https://user-images.githubusercontent.com/2203586/101181653-248a6a80-361b-11eb-9e90-5c2d0ed4f4fa.png)

**Comment by sylus** [comment]
Hi @PCH-TanB can you file this on Drupal.org?

I have reproduced this on another site so I will work on providing a fix and put the patch on D.O when u submit the issue :D 

Thanks so much for your help :D
