### ISSUE TITLE
Is there a fix with 8.8.12 with the latest security advisory?

### ISSUE THREAD

**Issue by PCH-TanB** [drupalwxt/wxt#241]
Hello,
I believe that the latest version 8.8.12 is affected by this:
https://cyber.gc.ca/en/alerts/drupal-security-advisory-12
https://www.drupal.org/sa-core-2021-001

Would you be able to provide a release with 8.8 for that?
Thanks and have a good day!
Bobby

**Comment by sylus** [comment]
A 4.0.0 release has been provided immediately.

I have committed to doing a 8.9 release since 8.8 is EOL now so will be sometime this week:

See: https://www.drupal.org/project/wxt/issues/3192398
