### ISSUE TITLE
Update to latest D9 core (9.1.5)

### ISSUE THREAD

**Issue by liquidcms** [drupalwxt/wxt#246]
Right now this project is at core 9.0.11 and core is at 9.1.5. I overrode wxt's dependencies with this:

    "drupal/core": "9.1.5 as 9.0.11",

in our local composer.json and the site seems to be functioning fine (not extensive tests for sure). Almost all the patches no longer apply - many are over 5 years old.

Also, i see in the changelog you are at version 4.0.3 of WxT; but that tag was never pushed.

Any plan for updating to latest core. If i do a PR for this is likely to get merged?

**Comment by olstjos** [comment]
see Drupal.org issue: https://www.drupal.org/project/wxt/issues/3207628
