### ISSUE TITLE
New 8.9 release for SA-CORE-2021-002

### ISSUE THREAD

**Issue by nfrenette** [drupalwxt/wxt#249]
Hello WxT team,

Is a new release planned for this advisory?
https://www.drupal.org/sa-core-2021-002

Thank you!

**Comment by nathanpw** [comment]
I was about to make one, wxt 3.0.20, only updating drupal core. There is already one for Drupal 9 (wxt 4.0.4)

**Comment by nathanpw** [comment]
3.0.23 was released last night, we had issues with the d.o packager. We would like this to be the last 3.x.x release of wxt. As such we would strongly suggest moving tot eh 4.x version and Drupal 9.
