### ISSUE TITLE
Readme.md Broken reference link

### ISSUE THREAD

**Issue by ECJana** [drupalwxt/wxt#251]
Readme.md broken link on the Azure Diagram (https://github.com/drupalwxt/helm-drupal/blob/master/docs/azure-aks-infra.pdf).

Sorry if this is not how to report this type of issue.

**Comment by sylus** [comment]
Thank you so much @ECJana i fixed this link up :D 

https://github.com/drupalwxt/wxt/commit/5d12b247d6b8b3b5eacbbd2a7e8b45554607c607

**Comment by ECJana** [comment]
Thank you for actioning this so fast. Cheers.
