### ISSUE TITLE
Process to upgrade Drupal 8.9.13 (wxt-3.0.19) to Drupal 9

### ISSUE THREAD

**Issue by chrixed** [drupalwxt/wxt#252]
Hi,
Im having some issue upgrading our Drupal 8.9.13 (wxt-3.0.19) to Drupal 9 (wxt-4.0.4)

I've replace the complete file system and when running the drush cache:rebuild, I'm getting a error:
 The service "book.breadcrumb" has a dependency on a non-existent service "entity.manager".
 
 Do you have specific instructions to run this upgrade?
 
 Thank you

**Comment by sylus** [comment]
I believe this will help:

https://www.drupal.org/project/wxt/issues/3182648

But your issue seems related to the book module which I think needs some patches for it to be compatible with D9.

Maybe this is related?

```
                "2470896 - Make Book navigation translatable":
                "https://www.drupal.org/files/issues/2020-12-02/2470896_223.patch",
```
