### ISSUE TITLE
Install wxt 3.0.23 security patch

### ISSUE THREAD

**Issue by chrixed** [drupalwxt/wxt#253]
Hi,
We are running Wxt 8.9.13 and we would like to avoid installing the wxt 3.0.23 security patch and jump directly to Drupal 9

Which release should I download to upgrade from 8.9.13 to 9 directly?

Note: Our server don't have internet access so we would need the complete tarball installation

Thanks 
Chris

**Comment by sylus** [comment]
This issue should help i believe ^_^

https://www.drupal.org/project/wxt/issues/3182648
