### ISSUE TITLE
Help in upgrading Drupal 8.9.13 (wxt-3.0.19) to Drupal 9 (wxt-4.0.4)

### ISSUE THREAD

**Issue by chrixed** [drupalwxt/wxt#256]
We are running an upgrade to Drupal 9 (wxt 4.0.4) using tarball and do a complete file system replace.
Note this server don't have internet access.

We are now getting the following error when trying drush9 update:cache and this even after we have replaced entity.manager with entity_type.manager
  [Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]
  The service "sanitize.userfields.commands" has a dependency on a non-existent service "entity.manager".
  
  We have replace entity.manager with entity_type.manager
  
  Anybody have an idea?

Thanks

**Comment by sylus** [comment]
If possible cna you file this issue over at drupal.org/project/wxt ?

Thx!

**Comment by chrixed** [comment]
We have opened a request to give our intranet server access to internet which will open the option of an upgrade through Drupal wxt.

Thank you
