### ISSUE TITLE
Webform patch no longer applying

### ISSUE THREAD

**Issue by sjpeters79** [drupalwxt/wxt#259]
Getting the following error when building a new drupal 9 site:

Could not apply patch! Skipping. The error was: Cannot apply patch https://www.drupal.org/files/issues/2021-05-07/3212867-3.patch
                                                                              
  [Exception]                                                                  
  Cannot apply patch Enter drupal/webform patch #3212867 description here (ht  
  tps://www.drupal.org/files/issues/2021-05-07/3212867-3.patch)!               

The issue appears to have been fixed and merged into the latest webform release:
https://www.drupal.org/node/3212867

**Comment by smulvih2** [comment]
Linking to Drupal.org issue - https://www.drupal.org/project/wxt/issues/3220695
