### ISSUE TITLE
Updated Drupal core release

### ISSUE THREAD

**Issue by markwooff** [drupalwxt/wxt#263]
Hi DrupalWxT team,

I was just curious if there were any plans for a new release in the near future? There have been a few CVEs issued since the last [4.1.0](https://github.com/drupalwxt/wxt/releases/tag/4.1.0) release and we were hoping to use one of your patched Docker images as we have in the past. The latest CVEs range from https://www.drupal.org/sa-core-2021-005 all the way to https://www.drupal.org/sa-core-2021-010

We understand that this is all open-source and that updates take time so know that the work you do is very much appreciated!

**Comment by sylus** [comment]
This should be coming out at some point today!
