### ISSUE TITLE
"entity.manager" replace by "entity.type.manager"

### ISSUE THREAD

**Issue by chrixed** [drupalwxt/wxt#265]
Hi,
Does anybody created a patch for "entity.manager" replace by "entity.type.manager" instead of manually replacing it in code base?
We are running wxt 3.9.16 and we are trying to update with 4.0.0 to gradually make our way up to wxt 4.0.4 (Drupal 9)

Thanks 
Chris

**Comment by sylus** [comment]
We have done this for all of the base modules, if you are using some contrib then you will have to make a patch and then add that patch to your composer.json file.

Hope this helps!
