### ISSUE TITLE
Canada.ca flyout menu is broken.

### ISSUE THREAD

**Issue by liquidcms** [drupalwxt/wxt#268]
I reported this a couple months back against WxT Bootstrap on D.org (https://www.drupal.org/project/wxt_bootstrap/issues/3236799); but guessing not a lot of attention to that queue; so figured I should also post here.

![menu set up](https://www.drupal.org/files/issues/2021-09-20/menu1.png)
![outcome](https://www.drupal.org/files/issues/2021-09-20/menu2.png)

**Comment by liquidcms** [comment]
this seems to mostly fix it.. but more testing to do yet

```
.slflnk.expanded.dropdown.open ul.sm {
  display: block;
}
.slflnk.expanded.dropdown ul.sm {
  display: none;
}
```

**Comment by liquidcms** [comment]
This is just a small piece of the issue; i see that the flyout portions are only on click (supposed to be on hover) and they are not positioned correctly. I see the code for acting on hover and it is being hit but failing at some point (no error). My guess is there is a class wrapper missing from the entire menu which makes the wet portions of this work... but comparing to what's on canada.ca i don't see it.

**Comment by liquidcms** [comment]
the following fixes the menu (externally, not in the WxT distribution). My guess is that some of this is added in WxT and they made a change to WET which has not been taken into account in WxT updates (as classes are missing and css is wrong).

JS:
`$('nav#wb-auto-2 a.dropdown-toggle').attr('aria-haspopup', 'true');`

CSS:
```
.gcweb-menu a[aria-expanded="true"] + ul.sm {
  display: block;
}
.expanded.dropdown ul.sm {
  display: none;
}

.gcweb-menu .dropup,
.gcweb-menu .dropdown {
  position: static;
}
```

As a side note, its startling how poor the structure of this menu is (parent items faked in css to look like parents) and how poorly the WET JS code is written in general. Spelling mistakes, formatting is extremely inconsistent with spaces and blank lines scattered around all over. Odd this has never been cleaned up or better, some sort of jslint rule set defined for it.

**Comment by liquidcms** [comment]
and a better version:

JS:
` $('nav.gcweb-menu a.dropdown-toggle').attr('aria-haspopup', 'true');`

CSS:
```
.gcweb-menu a[aria-expanded="true"] + ul.sm {
  display: block;
}
.expanded.dropdown ul.sm {
  display: none;
}

.gcweb-menu .dropup,
.gcweb-menu .dropdown {
  position: static;
}
```

**Comment by sylus** [comment]
Apologies I finally got time to take a look at this and believe I have it fixed.

I documented the fixes over in the issue:

https://www.drupal.org/project/wxt/issues/3236799#comment-14347979
