### ISSUE TITLE
New To DrupalWxT

### ISSUE THREAD

**Issue by TinoTran-Work** [drupalwxt/wxt#291]
Hello,

I'm attempting to setup and install DrupalWxT but am running into a few issues.  Firstly, I have installed Drupal for the first time using Composer.  From what I understand in the [documentation](https://drupalwxt.github.io/en/docs/general/installation/), I should be able to run the composer command, setup IIS to point to that new folder and do the installation.  This isn't working presently.  Is there a tutorial on how to setup DrupalWxT so that I could have a test site up and running?

I also am having an issue where the CSS isn't working from Drupal.  I understand this may not be an issue you can help resolve, but any knowledge or suggestions would be great!

Thank you for your time.  Have a marvelous day!

**Comment by smulvih2** [comment]
@TinoTran-Work when I first read this I was going to point you to [https://drupalwxt.github.io/en/docs/general/installation/](https://drupalwxt.github.io/en/docs/general/installation), but it looks like you already have reference to that install guide. What exactly are you having trouble with?

**Comment by TinoTran-Work** [comment]
After running the commands I map an IIS Application to the folder.  However, I get Forbidden (due to directory browsing).  I'm unable to find which folder to map the site for installation to start. 

composer create-project drupalwxt/site-wxt:9.4.x-dev wxtDrupal --no-interaction
composer create-project drupalwxt/wxt-project:4.4.0 wxt

The above are the two commands I had ran to install the sites.

**Comment by rgalipeau** [comment]
Have you ever gotten basic Drupal running in IIS first? If your composer ran clean without errors… it’s likely your IIS. Maybe try Nginx/Apache. 
It’s just not as well documented with IIS. We’ve done it a rare few times, but it’s “different”, and you’ll be fighting permissions IIS gauntlet.

**Comment by TinoTran-Work** [comment]
Hello!  I took your advice and deployed it with Apache in Linux environment.  I created a new issue as this initial issue has been resolved.  Thank you!

**Comment by TinoTran-Work** [comment]
THank you!
