### ISSUE TITLE
Error on Installation

### ISSUE THREAD

**Issue by TinoTran-Work** [drupalwxt/wxt#296]
Hello,

I finally got to the installation of DrupalWxt, but got an error when installing the extensions.  How do I get back to the installation or remove the issue extension?

Error Message: The website encountered an unexpected error. Please try again later.

Drupal\Component\Plugin\Exception\PluginNotFoundException: The "metatag_display_extender" plugin does not exist. Valid plugin IDs for Drupal\views\Plugin\ViewsPluginManager are: default in Drupal\Core\Plugin\DefaultPluginManager->doGetDefinition() (line 53 of core/lib/Drupal/Component/Plugin/Discovery/DiscoveryTrait.php).

Thank you for your time.  Have a wonderful day!

**Comment by sylus** [comment]
Hi there I think you should file an issue over at https://drupal.org/project/wxt

However I would need much more information then this basically the exact steps you used and branch etc.

At first glance seems related to this https://www.drupal.org/project/metatag/issues/2927551#comment-13677219

But I have not seen this error and the CI which tests every commit hasn't either.

Hope this helps!
