### ISSUE TITLE
S3FS?

### ISSUE THREAD

**Issue by liquidcms** [drupalwxt/wxt#300]
I see the WxT composer.json has patches (which are not current) for S3FS, even though it does not explicitly load S3FS. It is possible that S3FS it is a dependency of some other project which is loaded (poor way to manage with composer); but i suspect not the case.

**Comment by sylus** [comment]
Hi there ^_^

This was from quite a while ago when we had s3fs bundled before reduced the size of distro and also there were better ways of handling persistent storage via Azure Files NFS mounting so this is no longer needed.

I removed the patches since they should no longer be there :)

**Comment by liquidcms** [comment]
We'll likely still end up using S3FS as i dont think an NFS mount will offer the same solution. We are trying to not have default scaffold backup system backup the private files folder. A solution is to slice off specific folders to S3 and as such; they will not be included in a tar script; whereas an NFS mount would still be seen by tar.

But that patch is old, so thanks for removing.

**Comment by liquidcms** [comment]
but crept back in to 5.x

**Comment by sylus** [comment]
Thank you!

I removed this again, my apologies!
