### ISSUE TITLE
Drupal console site:install results in configuration error (system.theme).

### ISSUE THREAD

**Issue by jazty** [drupalwxt/wxt#99]
Hello
Every time I try to do a site install using Drupal console or otherwise I end up with the following error:

```
$ drupal site:install wxt --langcode="en"

...
...

Starting Drupal 8 install process

[ERROR] Configuration objects (system.theme) provided by system already exist in active configuration
```

Any known fix?

**Comment by nathanv** [comment]
Which version are you using? The latest tag passed CI: https://travis-ci.org/drupalwxt/wxt/builds/318897924

If the CI is working then if you try out what's prescribed https://github.com/drupalwxt/wxt/blob/2.0.0-rc10/.travis.yml and you should be good.

@jazty we have a `Make drupal_install` target as part of our composer / docker workflow here:
https://github.com/drupalwxt/site-wxt/blob/8.x/Makefile that points to https://github.com/drupalwxt/site-wxt/blob/8.x/docker/bin/cli ... very much so
 [recommended](http://drupalwxt.github.io/workflow/composer/#what-does-the-template-do).

I highly recommend looking into our composer project https://github.com/drupalwxt/site-wxt as that will get you up and running more quickly on top of docker/composer/alpine ... and facilitate using a CI whether you're using travis or gitlab.

cc @sylus @LaurentGoderre for comment

**Comment by sylus** [comment]
@zachomedia I remember you said u came across this but when we both looked ourselves couldn't reproduce. Since u had roughly same issue can u let me know what did to resolve?

**Comment by zachomedia** [comment]
@sylus I think it has to do with one of the failing patches (there are 3 according to the latest build of site-wxt https://travis-ci.org/drupalwxt/site-wxt/jobs/317739243#L912).

**Comment by zachomedia** [comment]
@jazty Just an update for you - we're waiting on lightning to fix a few things before we can get an updated wxt release out. Then we can test again and hope that it fixes the issue that you're running into.

**Comment by zachomedia** [comment]
@jazty A new release of WxT is out, can you try again with the latest version (2.0.1)?

**Comment by jazty** [comment]
Excellent! It installs fine now. Thanks @zachomedia

**Comment by zachomedia** [comment]
Great! Thanks for the update.
